blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_view/<int:pk>', cache_page(60)(BlogDetailView.as_view()), name='blog_view'),
    path('blog_update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, password_res, PasswordResetView, UserListView, \
    UserDetailView, toggle_activity

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>', email_verification, name='email_verification'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_res/', password_res, name='password_res'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('user_detail/<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('toggle_activity/<int:pk>/', toggle_activity, name='toggle_activity'),
    ]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': 'True', 'blank': 'True'}


class User(AbstractUser):
    username = None
    email = models.EmailField(max_length=35, verbose_name='Email', unique=True)
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE, help_text='Номер телефона')
    token = models.CharField(max_length=35, verbose_name='token', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('deactivate_user', 'Can deactivate user'),
            ('view_all_users', 'Can view all users'),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from mailing.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class PasswordResetForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

users/views.py
import secrets
import random

from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, FormView, ListView, DetailView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, PasswordResetForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email_confirm/{token}'
        send_mail(
            subject='Подтверждение почты',
            message=f'Перейдите по ссылке для подтверждения почты: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def password_res(request):
    if request.method == 'POST':
        email = request.POST['email']
        user = get_object_or_404(User, email=email)
        new_password = ''.join([str(random.randint(0, 9)) for i in range(12)])
        send_mail(
            subject='Вы сменили пароль',
            message=f'Ваш новый пароль: {new_password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        user.set_password(new_password)
        user.save()
        return redirect('users:login')
    return render(request, 'users/reset_password.html')


class PasswordResetView(FormView):
    template_name = 'password_reset.html'
    form_class = PasswordResetForm
    success_url = reverse_lazy('users:login')


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_all_users'


@permission_required('users.deactivate_user')
def toggle_activity(request, pk):
    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse('users:user_list'))


class UserDetailView(PermissionRequiredMixin, DetailView):
    model = User

users/templates/login.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <form method="post" class="form-floating">
        {% csrf_token %}
        <div class="row text-start">
            <div class="col-lg-3 col-md-6 col-sm-12 mx-auto">
                <div class="card mb-4 box-shadow mx-auto">
                    <div class="card-header text-center">
                        <h4 class="my-0 font-weight-normal">Авторизация</h4>
                    </div>
                    <div class="card-body text-center">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Войти
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/password_reset.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <form method="post" action="{% url 'users:password_res' %}" enctype="multipart/form-data" class="form-floating">
        {% csrf_token %}
        <div class="row text-start">
            <div class="col-lg-3 col-md-6 col-sm-12 mx-auto">
                <div class="card mb-4 box-shadow mx-auto">
                    <div class="card-header text-center">
                        <h4 class="my-0 font-weight-normal">Восстановление пароля</h4>
                    </div>
                    <div class="card-body text-center">
                        <div class="row text-center mb-3">
                            <input type="email" name="email" class="form-control" id="email" placeholder="E-mail для восстановления" required>
                        </div>
                        <button type="submit" class="btn btn-block btn-outline-primary">Отправить пароль</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}