blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_view/<int:pk>', cache_page(60)(BlogDetailView.as_view()), name='blog_view'),
    path('blog_update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL)

mailing/urls.py
from django.urls import path
from django.conf.urls.static import static

from config import settings
from mailing.apps import MailingConfig
from mailing.views import (HomeView, ClientListView, ClientUpdateView, ClientCreateView, ClientDeleteView,
                           ClientDetailView, MessageListView, MessageUpdateView, MessageCreateView, MessageDeleteView,
                           MessageDetailView, MailingListView, MailingUpdateView, MailingCreateView, MailingDeleteView,
                           MailingDetailView, LogListView)

app_name = MailingConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('list/', ClientListView.as_view(), name='client_list'),
    path('update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
    path('delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('view/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('message_view/<int:pk>', MessageDetailView.as_view(), name='message_view'),
    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing_view/<int:pk>', MailingDetailView.as_view(), name='mailing_view'),
    path('log_list/', LogListView.as_view(), name='log_list'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/models.py
from django.db import models
from users.models import User
from config import settings


NULLABLE = {'null': 'True', 'blank': 'True'}


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='почта')
    name = models.CharField(max_length=50, verbose_name='Ф.И.О')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    comment = models.CharField(max_length=100, verbose_name='комментарий', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                              **NULLABLE)

    def __str__(self):
        return f'{self.name} - {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('email',)


class Message(models.Model):
    theme = models.CharField(max_length=100, verbose_name='тема письма')
    text = models.TextField(verbose_name='тело письма')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                              **NULLABLE)

    def __str__(self):
        return self.theme

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ('theme',)


class Mailing(models.Model):

    DAILY = "Раз в день"
    WEEKLY = "Раз в неделю"
    MONTHLY = "Раз в месяц"

    PERIOD_CHOICES = [
        (DAILY, "Раз в день"),
        (WEEKLY, "Раз в неделю"),
        (MONTHLY, "Раз в месяц"),
    ]

    CREATED = "Создана"
    STARTED = "Запущена"
    COMPLETED = "Завершена"

    STATUS_CHOICES = [
        (COMPLETED, "Завершена"),
        (CREATED, "Создана"),
        (STARTED, "Запущена"),
    ]

    name = models.CharField(max_length=150, verbose_name="Название")
    description = models.TextField(**NULLABLE, verbose_name="Описание")
    status = models.CharField(max_length=150, choices=STATUS_CHOICES, default=CREATED, verbose_name="Статус")
    periodicity = models.CharField(
        max_length=150,
        choices=PERIOD_CHOICES,
        default=DAILY,
        verbose_name="Периодичность",
    )
    start_date = models.DateTimeField(
        verbose_name="Дата начала",
        **NULLABLE,
    )
    end_date = models.DateTimeField(verbose_name='Дата окончания', **NULLABLE, help_text='не обязательное поле')
    next_send_time = models.DateTimeField(verbose_name='Время следующей отправки', **NULLABLE)
    clients = models.ManyToManyField(Client, related_name='mailing', verbose_name='Клиенты рассылки')
    message = models.ForeignKey(Message, verbose_name='Cообщение', on_delete=models.CASCADE, **NULLABLE)
    owner = models.ForeignKey(User, verbose_name='Владелец',  on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f"{self.name}, статус: {self.status}"

    def save(self, *args, **kwargs):
        if not self.next_send_time:
            self.next_send_time = self.start_date
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ("name",)
        permissions = [
            ('deactivate_mailing', 'Can deactivate mailing'),
            ('view_all_mailings', 'Can view all mailings'),
        ]


class Log(models.Model):

    SUCCESS = 'Успешно'
    FAIL = 'Неуспешно'
    STATUS_CHOICES = [
        (SUCCESS, 'Успешно'),
        (FAIL, 'Неуспешно'),
    ]

    time = models.DateTimeField(
        verbose_name="Дата и время попытки", auto_now_add=True
    )
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, verbose_name='Cтатус')
    server_response = models.CharField(
        max_length=150, verbose_name="Ответ сервера почтового сервиса", **NULLABLE
    )
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name="Рассылка")

    def __str__(self):
        return f"{self.mailing} {self.time} {self.status} {self.server_response}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылки"

mailing/forms.py
from django import forms

from mailing.models import Client, Mailing, Message

forbidden_words = ['казино',
                   'криптовалюта',
                   'крипта',
                   'биржа',
                   'дешево',
                   'бесплатно',
                   'обман',
                   'полиция',
                   'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = ('owner',)


class ManagerMailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('status',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)

    def clean_theme(self):
        cleaned_data = self.cleaned_data['theme']
        for word in forbidden_words:
            if word.lower() in cleaned_data.lower():
                raise forms.ValidationError('Название не должно содержать запрещённых слов')
            else:
                return cleaned_data

    def clean_text(self):
        cleaned_data = self.cleaned_data['text']
        if cleaned_data.lower() in forbidden_words:
            raise forms.ValidationError('Описание не должно содержать запрещённых слов')
        return cleaned_data

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.services import get_articles_from_cache
from mailing.forms import ClientForm, MessageForm, MailingForm, ManagerMailingForm
from mailing.models import Mailing, Client, Message, Log


class HomeView(TemplateView):
    template_name = 'mailing/index.html'
    extra_context = {
        'title': 'Сервис рассылок'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        mailings = Mailing.objects.all()
        clients = Client.objects.all()
        context_data['all_mailings'] = mailings.count()
        context_data['active_mailings'] = mailings.filter(status=Mailing.STARTED).count()
        context_data['active_clients'] = clients.values('email').distinct().count()

        context_data['random_blogs'] = get_articles_from_cache().order_by('?')[:3]
        return context_data


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form = ClientForm
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form = ClientForm
    form_class = ClientForm

    def get_success_url(self):
        return reverse('mailing:client_list', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form = MessageForm
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form = MessageForm
    form_class = MessageForm

    def get_success_url(self):
        return reverse('mailing:message_view', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form = MailingForm
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form = MailingForm
    form_class = MailingForm

    def get_success_url(self):
        return reverse('mailing:mailing_view', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return MailingForm
        elif user.has_perm('mailing.deactivate_mailing'):
            return ManagerMailingForm
        else:
            raise PermissionDenied


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager') and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class LogListView(LoginRequiredMixin, ListView):
    model = Log

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cервис рассылок</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">


    <link href="{% static 'css/boottrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
        
    </style>


</head>
<body>

<header data-bs-theme="dark">
    <div class="text-bg-dark">
        <div class="container">
            <div class="row">
                {% include 'mailing/includes/inc_menu.html' %}
            </div>
        </div>
    </div>
</header>

<main>

    {% block content %}
    {% endblock %}

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="/">Главная</a>
        </p>
        <p>&copy; 2024 - {% now 'Y' %}</p>
    </div>
</footer>

</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="text-center">
    <div class="container">
        <h1>Удаление клиента</h1>
    </div>
</section>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента "{{ client.name }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html'%}
{% block content %}
<section class="text-center">
    <div class="container">
        <h1>Информация о клиенте</h1>
    </div>
</section>
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">Имя клиента: {{ client.name }}</p>
                        <p class="card-text">Email: {{ client.email }}</p>
                        <p class="card-text">Комментарий: {{ client.comment }}</p>
                        <p class="card-text">Добавил клиента: {{ client.owner }}</p>
                        <a class="btn btn-primary" href="{% url 'mailing:client_list' %}" role="button">Назад</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <a class="btn btn-outline-primary mb-5" href="{% url 'mailing:client_create' %}">Добавить клиента</a>
        </div>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for client in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <p class="h4 card-text">{{ client.name }}</p>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ client.email }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'mailing:client_detail' client.pk %}"
                                   role="button">Просмотр</a>
                                <a class="btn btn-primary" href="{% url 'mailing:client_update' client.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'mailing:client_delete' client.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html'%}
{% block content %}
<section class="text-center">
    <div class="container">
        <h1>В данный момент на сайте</h1>
    </div>
</section>
<br>
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <p class="h5 card-text">Клиентов: {{ active_clients }}</p>
                        <p class="h5 card-text">Активных рассылок: {{ active_mailings }}</p>
                        <p class="h5 card-text">Всего рассылок: {{ all_mailings }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>

{% if user.is_authenticated %}
<div class="container">

        <a class="btn btn-primary mb-7" href="{% url 'mailing:client_create' %}">Добавить клиента</a>
        <a class="btn btn-primary mb-7" href="{% url 'mailing:mailing_create' %}">Добавить рассылку</a>
        <a class="btn btn-primary mb-7" href="{% url 'mailing:message_create' %}">Добавить сообщение</a>
</div><br>
{% endif %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for object in random_blogs %}
            <div class="col-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">
                        <h2>{{ object.title}}</h2>
                        <p class="card-text">Содержание: {{ object.body }}</p>
                        <p class="card-text"> Создана {{ object.created_at }}</p>
                        <p class="card-text">Просмотры- {{ object.views_count }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/log_list.html
{% extends 'mailing/base.html'%}
{% block content %}

<div class="container">
    <h1>Попытки рассылок</h1>
</div>

<div class="container">
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Рассылка</th>
        <th scope="col">Время</th>
        <th scope="col">Статус</th>
        <th scope="col">Ответ сервера</th>
    </tr>
    </thead>
    <tbody>
    {% for log in object_list %}
    <tr>
        <td>{{ log.mailing }}</td>
        <td>{{ log.time }}</td>
        <td>{{ log.status }}</td>
        <td>{{ log.server_response }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="text-center">
    <div class="container">
        <h1>Удаление рассылки</h1>
    </div>
</section>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку "{{ mailing.name }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html'%}
{% block content %}
<section class="text-center">
    <div class="container">
        <h1>Просмотр сообщения</h1>
    </div>
</section>
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">Название: {{ mailing.name }}</p>
                        <p class="card-text">Описание: {{ mailing.description }}</p>
                        <p class="card-text">Статус: {{ mailing.status }}</p>
                        <p class="card-text">Периодичность: {{ mailing.periodicity }}</p>
                        <p class="card-text">Дата начала: {{ mailing.start_date }}</p>
                        <p class="card-text">Дата окончания: {{ mailing.end_date }}</p>
                        <p class="card-text">Время следующей отправки: {{ mailing.next_send_time }}</p>
                        <p class="card-text">Тема сообщения: {{ mailing.message }}</p>
                        <p class="card-text">Автор: {{ mailing.owner }}</p><br>
                        <p class="card-text h5">Клиенты рассылки: </p>
                        {% for client in mailing.clients.all %}
                        <p class="card-text"> {{ client.email }}</p>
                        {% endfor %}
                        <a class="btn btn-primary" href="{% url 'mailing:mailing_list' %}" role="button">Назад</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <br>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <form method="post" class="row">
            <div class="col-12">
                <div class="card shadow-sm">
                    <div class="card-header h3">
                        {% if object %}
                        Редактирование рассылки
                        {% else %}
                        Добавление рассылки
                        {% endif %}
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить изменения
                            {% else %}
                            Создать сообщение
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <a class="btn btn-outline-primary mb-5" href="{% url 'mailing:mailing_create' %}">Создать рассылку</a>
        </div>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for mailing in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <p class="h4 card-text">{{ mailing.name }}</p>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ mailing.description }}</p>
                        <small class="text-body-secondary">Периодичность: {{ mailing.periodicity }}</small><br>
                        <small class="text-body-secondary">Дата начала: {{ mailing.start_date }}</small><br>
                        <small class="text-body-secondary">Дата окончания: {{ mailing.end_date }}</small><br>
                        <small class="text-body-secondary">Статус: {{ mailing.status }}</small><br><br>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'mailing:mailing_view' mailing.pk %}"
                                   role="button">Просмотр</a>
                                <a class="btn btn-primary" href="{% url 'mailing:mailing_update' mailing.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'mailing:mailing_delete' mailing.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <a class="btn btn-outline-primary mb-5" href="{% url 'mailing:message_create' %}">Добавить сообщение</a>
        </div>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for message in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <p class="h4 card-text">{{ message.theme }}</p>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ message.text | slice:100 }} ...</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'mailing:message_view' message.pk %}"
                                   role="button">Просмотр</a>
                                <a class="btn btn-primary" href="{% url 'mailing:message_update' message.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'mailing:message_delete' message.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}