blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_view/<int:pk>', cache_page(60)(BlogDetailView.as_view()), name='blog_view'),
    path('blog_update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL)

blog/models.py
from django.db import models

NULLABLE = {'null': 'True', 'blank': 'True'}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='products/', verbose_name='Превью', **NULLABLE)
    created_at = models.DateField(verbose_name='Дата создания', auto_now_add=True)
    is_published = models.BooleanField(verbose_name='Опубликовано', default=True)
    views_count = models.PositiveSmallIntegerField(verbose_name='Просмотры', default=0)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('created_at',)

blog/forms.py
from django import forms

from blog.models import Blog
from mailing.forms import forbidden_words, StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'image']

    def clean_title(self):
        cleaned_data = self.cleaned_data['name']
        for word in forbidden_words:
            if word.lower() in cleaned_data.lower():
                raise forms.ValidationError('Заголовок не должен содержать запрещённых слов')
            else:
                return cleaned_data

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from blog.services import get_articles_from_cache


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'content', 'image', )
    success_url = reverse_lazy('blog:blog_list')


class BlogListView(ListView):
    model = Blog

    extra_context = {
        'title': 'Блог'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = get_articles_from_cache().filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content', 'image', )
    success_url = reverse_lazy('blog:blog_list')

    def get_success_url(self):
        return reverse('blog:blog_view', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="text-center">
    <div class="container">
        <h1>Удаление статьи</h1>
    </div>
</section>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить статью "{{ blog.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html'%}
{% load my_tags %}
{% block content %}
<section class="text-center">
    <div class="container">
        <h1>Просмотр статьи</h1>
    </div>
</section>
<div class="container">
    <div class="col-12">
        <img src="{{ blog.image | mymedia }}" class="card-img-top">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">Заголовок: {{ blog.title }}</p>
                        <p class="card-text">Содержание: {{ blog.content }}</p>
                        <p class="card-text">Дата добавления: {{ blog.created_at }}</p>
                        <p class="card-text">Просмотры: {{ blog.views_count }}</p>
                        <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <br>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <form method="post" class="row">
            <div class="col-12">
                <div class="card shadow-sm">
                    <div class="card-header h3">
                        {% if object %}
                        Редактирование статьи
                        {% else %}
                        Добавление статьи
                        {% endif %}
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить изменения
                            {% else %}
                            Добавить статью
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <a class="btn btn-outline-primary mb-5" href="{% url 'blog:blog_create' %}">Добавить статью</a>
        </div>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for blog in object_list %}
            {% if blog.is_published %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <p class="h4 card-text">{{ blog.title }}</p>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ blog.content | slice:100 }} ...</p>
                        <small class="text-body-secondary">Создана: {{ blog.created_at }}</small><br>
                        <small class="text-body-secondary">Количество просмотров: {{ blog.views_count }}</small><br>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:blog_view' blog.pk %}"
                                   role="button">Просмотр</a>
                                <a class="btn btn-primary" href="{% url 'blog:blog_update' blog.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'blog:blog_delete' blog.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}